### ISSUE TITLE
sh start.sh  启动这个脚本失败了,咋整?

### ISSUE THREAD

**Issue by ithjz** [birdLark/LarkMidTable#28]
[root@xxxx      flinkx-1.8_release]# sh start.sh
flinkx starting ...
start.sh: line 3: -job: command not found
nohup: appending output to ‘nohup.out’
start.sh: line 5: -flinkconf: command not found
start.sh: line 7: -pluginRoot: command not found

sh ./bin/flinkx

-job './job/stream.json'

-flinkconf './flinkconf/' 

-pluginRoot './plugins/'

**Comment by wushuoyouting** [comment]
授权，绝对路径

**Comment by 18360267271** [comment]
> 授权，绝对路径

您好，我也出现了同样的问题，按照您的方法改完之后还是提示找不到命令，您能把您的start.sh贴一下吗，感谢！

**Comment by wushuoyouting** [comment]
/usr/local/src/flinkx-1.10/bin/flinkx \
-mode yarnPer \
-job $1 \
-pluginRoot /usr/local/src/flinkx-1.10/syncplugins \
-yarnconf /opt/cloudera/parcels/CDH/lib/hadoop/etc/hadoop \
-flinkLibJar /opt/cloudera/parcels/FLINK-1.10.1-BIN-SCALA_2.12/lib/flink/lib \
-queue default



在 2021-07-05 11:15:53，"18360267271" ***@***.***> 写道：

授权，绝对路径

您好，我也出现了同样的问题，按照您的方法改完之后还是提示找不到命令，您能把您的start.sh贴一下吗，感谢！
