### ISSUE TITLE
安装不成功，apache maven 不存在ojdbc6

### ISSUE THREAD

**Issue by xsliang** [birdLark/LarkMidTable#75]
在larkmidtable-web\
下执行mvn clean install ，提示

[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/oracle/ojdbc6/11.2.0.3/ojdbc6-11.2.0.3.pom
[WARNING] The POM for com.oracle:ojdbc6:jar:11.2.0.3 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/sqljdbc4/4.0/sqljdbc4-4.0.pom
[WARNING] The POM for com.microsoft.sqlserver:sqljdbc4:jar:4.0 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/oracle/ojdbc6/11.2.0.3/ojdbc6-11.2.0.3.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/sqljdbc4/4.0/sqljdbc4-4.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for web 2.1.2:
[INFO]
[INFO] web ................................................ SUCCESS [  0.501 s]
[INFO] rpc ................................................ SUCCESS [  4.710 s]
[INFO] core ............................................... SUCCESS [  1.590 s]
[INFO] admin .............................................. FAILURE [  7.965 s]
[INFO] assembly ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.284 s
[INFO] Finished at: 2022-02-08T13:26:55+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project admin: Could not resolve dependencies for project com.larkmidtable.cn:admin:jar:2.1.2: The following artifacts could not be resolved: com.oracle:ojdbc6:jar:11.2.0.3, com.microsoft.sqlserver:sqljdbc4:jar:4.0: Could not find artifact com.oracle:ojdbc6:jar:11.2.0.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

发现
https://repo.maven.apache.org/maven2/com/oracle/
下不存在ojdbc6

**Comment by xsliang** [comment]
按照
https://www.cnblogs.com/max-home/p/11817141.html
可以解决

**Comment by xsliang** [comment]
之后可能出现
[WARNING] The POM for com.microsoft.sqlserver:sqljdbc4:jar:4.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for web 2.1.2:
[INFO]
[INFO] web ................................................ SUCCESS [  0.336 s]
[INFO] rpc ................................................ SUCCESS [  4.039 s]
[INFO] core ............................................... SUCCESS [  1.292 s]
[INFO] admin .............................................. FAILURE [  2.597 s]
[INFO] assembly ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.630 s
[INFO] Finished at: 2022-02-08T14:36:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project admin: Could not resolve dependencies for project com.larkmidtable.cn:admin:jar:2.1.2: Failure to find com.microsoft.sqlserver:sqljdbc4:jar:4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

可通过mvnrepository.com下载。

**Comment by liu-yu-hao** [comment]
我一开始也出现了这个问题
我把原来的依赖成下面的了
然后就可以正常使用了

<dependency>
    <groupId>com.oracle.database.jdbc</groupId>
    <artifactId>ojdbc6</artifactId>
    <version>11.2.0.4</version>
</dependency>

**Comment by liu-yu-hao** [comment]
我一开始也出现了这个问题
我把原来的依赖成下面的了
然后就可以正常使用了
`
<dependency>
    <groupId>com.oracle.database.jdbc</groupId>
    <artifactId>ojdbc6</artifactId>
    <version>11.2.0.4</version>
</dependency>
`
后面sqljdbc4也报错，好像是微软已经开源了，直接用了
`
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.1.0.jre8</version>
</dependency>`
