### ISSUE TITLE
启动后exector有问题，没有页面

### ISSUE THREAD

**Issue by liu-yu-hao** [birdLark/LarkMidTable#76]
11:39:57.973 exe [web, executor ExecutorRegistryThread] INFO  c.l.c.t.ExecutorRegistryThread - >>>>>>>>>>> web registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='executor', regist
ryValue='192.168.80.172:9999', cpuUsage='1.3', memoryUsage='71.65', loadAverage='0.7'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting fail, StatusCode(405) invalid. for url : http://192.168.80.172:8080/api/registry, content=null]

**Comment by birdLark** [comment]
应该是日志吧，现在可以跑了，有日志了
