### ISSUE TITLE
任务启动问题

### ISSUE THREAD

**Issue by Su1024** [birdLark/LarkMidTable#81]
![image](https://user-images.githubusercontent.com/23012179/153563654-4eb99ec3-1bc4-4f46-a96b-27700376008b.png)
![image](https://user-images.githubusercontent.com/23012179/153563683-20f89617-2773-4052-bc4f-b84ab4d62762.png)
实例在执行之后 没有任何日志输出，感觉是没有启动，后端日志是一直JobScheduleHelper执行

**Comment by yangtzelsl** [comment]
遇到同样的问题，请问是否已得到解决？

**Comment by Li-dacheng** [comment]
- 遇到同样问题，执行任务后无日志，但后台有JobTriggerPoolHelper的log打印，将执行语句粘到命令行运行

<img width="691" alt="c16401c2eeb683397c2607997436855" src="https://user-images.githubusercontent.com/46306557/156127238-579db578-dd2a-4fe3-bead-2e3cf1ce8e2c.png">

- 发现python语法有问题，原flinkx的脚本为python2版本，已修改为python3版本并提交

<img width="816" alt="03f10a25b332f2bd85da67835b9fff0" src="https://user-images.githubusercontent.com/46306557/156127832-f116aa7a-e8df-4693-8e60-0086449e60e3.png">

- python脚本成功打印，但报出Java异常，检测知系统默认用的java11版本，改为java8即可：
![image](https://user-images.githubusercontent.com/46306557/156128309-77060c6f-cb90-4972-856e-51f8950a886c.png)
数据同步成功，系统刷新日志出来了：
<img width="627" alt="4e54a3218f43d8d6e1e9ce686ccea30" src="https://user-images.githubusercontent.com/46306557/156128510-22539d51-1dea-47a7-b094-d091c983d9c4.png">

- 但是，单独在系统点执行一次，仍旧无法运行，没有日志出现，不知哪里出了问题，现只能将语句粘出来执行才行
- 求更新debug

**Comment by Akihi11** [comment]
你好，云雀数据中台现在还能联系上吗？
